/**
 * js/report.js
 * Sistema de reportes en PDF - Academic Reading & Writing Hub
 */

window.logActivity = function(activityName, status) {

    let progress = JSON.parse(localStorage.getItem('studentProgress')) || {};

    // Si la actividad no existe, crearla
    if (!progress[activityName]) {
        progress[activityName] = [];
    }

    // Registrar evento
    progress[activityName].push({
        status: status,
        date: new Date().toLocaleString()
    });

    localStorage.setItem('studentProgress', JSON.stringify(progress));

    console.log("Progress updated:", activityName);
};


async function generateReport() {

    // Accedemos a jsPDF desde el objeto global
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const name = localStorage.getItem('studentName') || "Student";
    const email = localStorage.getItem('studentEmail') || "No Email Provided";
    const progress = JSON.parse(localStorage.getItem('studentProgress'));

    if (!progress || Object.keys(progress).length === 0) {
        alert("You haven't completed any activities yet!");
        return;
    }

    // --- ENCABEZADO ---
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(26, 42, 108);
    doc.text("ACADEMIC WRITING HUB - PROGRESS REPORT", 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Instructor: Dr. Arturo Rodríguez Zambrano, PhD.", 20, 28);
    doc.line(20, 32, 190, 32);

    // --- DATOS DEL ESTUDIANTE ---
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    doc.setFontSize(11);

    doc.text(`Student Name: ${name}`, 20, 45);
    doc.text(`Email Address: ${email}`, 20, 52);
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, 20, 59);

    // --- LISTADO DE ACTIVIDADES ---
    let y = 80;

    doc.setFont("helvetica", "bold");
    doc.text("Completed Activities & Scores:", 20, 72);
    doc.setFont("helvetica", "normal");

    for (const [lesson, events] of Object.entries(progress)) {

        const lastEvent = events[events.length - 1];

        doc.setFillColor(245, 245, 245);
        doc.rect(20, y - 5, 170, 8, 'F');

        // limpiar nombre del archivo
        const lessonName = lesson.split('/').pop().replace(".html","");

        doc.text(`• ${lessonName}: ${lastEvent.status}`, 25, y);

        doc.setFontSize(8);
        doc.setTextColor(120);
        doc.text(`(Last activity: ${lastEvent.date})`, 130, y);

        doc.setFontSize(11);
        doc.setTextColor(0);

        y += 12;

        if (y > 270) {
            doc.addPage();
            y = 20;
        }
    }

    // --- PIE DE PÁGINA ---
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
        "This is an automated report generated by the Academic Reading & Writing Hub.",
        20,
        285
    );

    // Descargar PDF
    const fileName = `Report_${name.replace(/\s+/g, '_')}.pdf`;
    doc.save(fileName);
}